ui {
  url = ${?UI_URL}
  email = ${?UI_EMAIL}
  pass = ${?UI_PASS}
}

db {
  db_url = ${?DB_URL}
  db_user = ${?DB_USER}
  db_pass = ${?DB_PASS}
}

api {
  base_uri = ${?API_BASE_URI}
  api_username = ${?API_USERNAME}
  api_password = ${?API_PASSWORD}
}

include "application-local.conf"